class BasicDb < ActiveRecord::Migration
  def self.up

    execute %{
-- ================================================================================
--   postgres SQL DDL Script File
-- ================================================================================


-- ===============================================================================
-- 
--   Generated by:      tedia2sql -- v1.2.12
--                      See http://tedia2sql.tigris.org/AUTHORS.html for tedia2sql author information
-- 
--   Target Database:   postgres
--   Generated at:      Sat Apr 14 09:32:34 2007
--   Input Files:       pd.dia
-- 
-- ================================================================================



-- Generated SQL Constraints Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia



-- Generated Permissions Drops
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia




-- Generated SQL View Drop Statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia



-- Generated SQL Schema Drop statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia



-- Generated SQL Schema
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia


-- sesses_timeslots
-- Association between sesses and timeslots
create table sesses_timeslots (
  sess_id                   serial not null,
  timeslot_id               serial not null,
  constraint pk_Sesses_timeslots primary key (sess_id,timeslot_id)
) ;

-- people
create table people (
  id                        serial not null,
  name                      varchar(255),
  classroom_id              int,
  grade                     int2,
  notes                     text,
  constraint pk_People primary key (id)
) ;

-- classrooms
create table classrooms (
  id                        serial not null,
  shortname                 varchar(20),
  name                      varchar(255),
  mingrade                  int2,
  constraint pk_Classrooms primary key (id)
) ;

-- requests
create table requests (
  id                        serial not null,
  person_id                 int,
  project_id                int,
  rank                      int2,
  constraint pk_Requests primary key (id)
) ;

-- projects
create table projects (
  id                        serial not null,
  abbrev                    varchar (8),
  shortname                 varchar (20),
  name                      text,
  description               text,
  notes                     text,
  mingrade                  int2,
  maxgrade                  int2,
  capacity                  int2,
  constraint pk_Projects primary key (id)
) ;

-- locations
create table locations (
  id                        serial not null,
  name                      varchar(255),
  constraint pk_Locations primary key (id)
) ;

-- timeslots
create table timeslots (
  id                        serial not null,
  day                       varchar(8),
  start                     varchar(8),
  stop                      varchar(8),
  constraint pk_Timeslots primary key (id)
) ;

-- sesses
create table sesses (
  id                        serial not null,
  project_id                int,
  location_id               int,
  constraint pk_Sesses primary key (id)
) ;

-- assignments
create table assignments (
  id                        serial not null,
  person_id                 int,
  sess_id                   int,
  role                      char,
  certainty                 int2,
  constraint pk_Assignments primary key (id)
) ;










-- Generated SQL Views
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia




-- Generated Permissions
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia



-- Generated SQL Insert statements
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia



-- Generated SQL Constraints
-- --------------------------------------------------------------------
--     Target Database:   postgres
--     SQL Generator:     tedia2sql -- v1.2.12
--     Generated at:      Sat Apr 14 09:32:33 2007
--     Input Files:       pd.dia

alter table people add constraint people_fk_Classroom_id
  foreign key (classroom_id)
  references classrooms (id)  ;
alter table requests add constraint requests_fk_Person_id
  foreign key (person_id)
  references people (id)  ;
alter table requests add constraint requests_fk_Project_id
  foreign key (project_id)
  references projects (id)  ;
alter table sesses add constraint sesses_fk_Project_id
  foreign key (project_id)
  references projects (id)  ;
alter table sesses add constraint sesses_fk_Location_id
  foreign key (location_id)
  references locations (id)  ;
alter table sesses_timeslots add constraint sesses_timeslots_fk_SessesId
  foreign key (sess_id)
  references sesses (id) on delete cascade ;
alter table sesses_timeslots add constraint sesses_timeslots_fk_TimeslotsId
  foreign key (timeslot_id)
  references timeslots (id) on delete cascade ;
alter table assignments add constraint assignments_fk_Person_id
  foreign key (person_id)
  references people (id)  ;
alter table assignments add constraint assignments_fk_Sess_id
  foreign key (sess_id)
  references sesses (id)  ;
}

  end

  def self.down
  end
end
